### ISSUE TITLE
AttributeError: 'module' object has no attribute 'onemodel_v42_7'

### ISSUE THREAD

**Issue by kantajitshaw** [xiaomengyc/SG-One#4]
When I'm trying to run the scripts, it is giving the above-mentioned error.
Traceback (most recent call last):
  File "train_frame.py", line 14, in <module>
    from oneshot import *
AttributeError: 'module' object has no attribute 'onemodel_v42_7'

I think that some files are missing. Can you help by providing the files?
Thanks

**Comment by wangjiongw** [comment]
I met the same problem. And fortunately there is no missing files, but some naming errors. 
You can find that the proposed model is exactly defined in 'oneshot/onemodel_sg-one.py'.
I solved it by modifying the name in 'oneshot/__init__' to the actual file name, e.g. 'onemodel_sg-one'.
Also, the arch input should also be changed.

**Comment by li-yanling** [comment]
> I met the same problem. And fortunately there is no missing files, but some naming errors.
> You can find that the proposed model is exactly defined in 'oneshot/onemodel_sg-one.py'.
> I solved it by modifying the name in 'oneshot/**init**' to the actual file name, e.g. 'onemodel_sg-one'.
> Also, the arch input should also be changed.

Thanks. But after changing it to onemodel_sg-one, the new error name "onemodel_sg' is not defined comes out from train_frame.py line 62 model = eval(args.arch).OneModel(args). Did you meet the same error? Thank you.

**Comment by xiaomengyc** [comment]
Sorry for the later response. @heyPooPy is right. Btw, I have updated the oneshot/__init__.py file. Thanks!

**Comment by zhao123ying** [comment]
> > I met the same problem. And fortunately there is no missing files, but some naming errors.
> > You can find that the proposed model is exactly defined in 'oneshot/onemodel_sg-one.py'.
> > I solved it by modifying the name in 'oneshot/**init**' to the actual file name, e.g. 'onemodel_sg-one'.
> > Also, the arch input should also be changed.
> 
> Thanks. But after changing it to onemodel_sg-one, the new error name "onemodel_sg' is not defined comes out from train_frame.py line 62 model = eval(args.arch).OneModel(args). Did you meet the same error? Thank you.

sorry,I have met same problem with you.Do you deal with it?

**Comment by al3ms** [comment]
> onemodel_sg-one

Did you solve it?
I am facing the same problem.

**Comment by al3ms** [comment]
I get this error, anyone knows how to fix it?

Running parameters:

{
    "arch":"onemodel_sg-one",
    "max_steps":100001,
    "lr":1e-05,
    "disp_interval":100,
    "save_interval":5000,
    "snapshot_dir":"/content/drive/My Drive/sofa/SG-One/snapshots",
    "resume":false,
    "start_count":0,
    "split":"train",
    "group":1,
    "num_folds":4
}
Traceback (most recent call last):
  File "/content/drive/My Drive/sofa/SG-One/train_frame.py", line 159, in <module>
    train(args)
  File "/content/drive/My Drive/sofa/SG-One/train_frame.py", line 90, in train
    model, optimizer= get_model(args)
  File "/content/drive/My Drive/sofa/SG-One/train_frame.py", line 62, in get_model
    model = eval(args.arch).OneModel(args)
  File "<string>", line 1, in <module>
NameError: name 'onemodel_sg' is not defined
